apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "sample-please-replace"
---
apiVersion: akka.lightbend.com/v1
kind: AkkaMicroservice
metadata:
  name: $name$
  namespace: "sample-please-replace"
spec:
  replicas: 1
  image: <docker-registry>/$name$:<tag> 
  javaOptions: "-Xlog:gc -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75"
  resources:
    limits:
      memory: "2Gi"
    requests:
      memory: "2Gi"
      cpu: "1"
  jdbc:
    credentialsSecret: $name$-jdbc-secret
  kafka:
    credentialsSecret: $name$-kafka-secret
